### ISSUE TITLE
rails and mongoid integration test

### ISSUE THREAD

**Issue by koten0224** [koten0224/mongory#38]
```
# gemfiles/rails.gemfile
source "https://rubygems.org"

gem "rails"
gem "mongory", path: "../"

# gemfiles/mongoid.gemfile
source "https://rubygems.org"

gem "mongoid"
gem "mongory", path: "../"
```
workflow
```yaml
name: Mongory Matrix Test

on:
  push:
    branches: [main, dev]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        gemfile:
          - gemfiles/rails.gemfile
          - gemfiles/mongoid.gemfile
          - Gemfile # default

    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run RSpec
        run: bundle exec rspec
```

rspec
```ruby
RSpec.describe 'Mongory integration' do
  if defined?(Rails)
    it 'uses Rails present?/blank?' do
      expect(Mongory::Utils.new.send(:is_present?, "x")).to eq(true)
      expect(Mongory::Utils.new.send(:is_blank?, "")).to eq(true)
    end
  end

  if defined?(Mongoid)
    it 'registers Mongoid::Criteria::Queryable::Key' do
      converter = Mongory.condition_converter.key_converter
      registered = converter.instance_variable_get(:@registries).any? do |r|
        r.klass == Mongoid::Criteria::Queryable::Key
      end
      expect(registered).to be true
    end
  end
end
```
